# Makefile automatically generated by ghdl
# Version: GHDL 0.36-dev (v0.35-47-gbefe6faf) [Dunoon edition] - llvm code generator
# Command used to generate this makefile:
# ghdl --gen-makefile --workdir=work sr_tb

GHDL=ghdl
GHDLFLAGS= --workdir=work

# Default target
all: sr_tb

# Elaboration target
sr_tb: /usr/local/lib/ghdl/v93/ieee/std_logic_1164.o /usr/local/lib/ghdl/v93/ieee/std_logic_1164_body.o /usr/local/lib/ghdl/v93/ieee/numeric_std.o /usr/local/lib/ghdl/v93/ieee/numeric_std-body.o work/sr_tb.o work/shift_register.o
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: sr_tb
	$(GHDL) -r sr_tb $(GHDLRUNFLAGS)

# Targets to analyze files
/usr/local/lib/ghdl/v93/ieee/std_logic_1164.o: /usr/local/lib/ghdl/v93/ieee/../../src/ieee/std_logic_1164.v93
	@echo "This file was not locally built ($<)"
	exit 1
/usr/local/lib/ghdl/v93/ieee/std_logic_1164_body.o: /usr/local/lib/ghdl/v93/ieee/../../src/ieee/std_logic_1164_body.v93
	@echo "This file was not locally built ($<)"
	exit 1
/usr/local/lib/ghdl/v93/ieee/numeric_std.o: /usr/local/lib/ghdl/v93/ieee/../../src/ieee/numeric_std.v93
	@echo "This file was not locally built ($<)"
	exit 1
/usr/local/lib/ghdl/v93/ieee/numeric_std-body.o: /usr/local/lib/ghdl/v93/ieee/../../src/ieee/numeric_std-body.v93
	@echo "This file was not locally built ($<)"
	exit 1
work/sr_tb.o: sr_tb.vhdl
	$(GHDL) -a $(GHDLFLAGS) $<
work/shift_register.o: shift_register.vhdl
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
/usr/local/lib/ghdl/v93/ieee/std_logic_1164.o: 
/usr/local/lib/ghdl/v93/ieee/std_logic_1164_body.o:  /usr/local/lib/ghdl/v93/ieee/std_logic_1164.o
/usr/local/lib/ghdl/v93/ieee/numeric_std.o:  /usr/local/lib/ghdl/v93/ieee/std_logic_1164.o
/usr/local/lib/ghdl/v93/ieee/numeric_std-body.o:  /usr/local/lib/ghdl/v93/ieee/numeric_std.o
work/sr_tb.o:  /usr/local/lib/ghdl/v93/ieee/std_logic_1164.o /usr/local/lib/ghdl/v93/ieee/std_logic_1164_body.o /usr/local/lib/ghdl/v93/ieee/numeric_std.o /usr/local/lib/ghdl/v93/ieee/numeric_std-body.o
work/shift_register.o:  /usr/local/lib/ghdl/v93/ieee/std_logic_1164.o
